name: XWeather
main: me.Ccamm.XWeather.Main
author: Ccamm
version: 2.0.0
api-version: 1.13
softdepend: [Multiverse-Core, WorldGuard]
commands:
  xweather:
    description: For setting the weather
    usage: /xweather
permissions:
  xweather.admin:
    description: Allows the player to use xweather commands
    default: False